name=input("Enter your name:")
age=input("Enter your age:")
gender=input("Enter your gender:")
phone= input("ENter your number:")
email=input("Enter your email ID:")
address=input("Enter your address:")
city=input("Enter your city:")
nationality=input("Enter your nationality:")

print("\n----- Personal Details -----")
print("Name:", name)
print("Age:", age)
print("Gender:", gender)
print("Email:", email)
print("Address:", address)
print("City:", city)
print("Nationality:", nationality)